# -*- coding: utf-8 -*-
"""Pollution_Final.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HI_NQSt4X7marhjpgxPDC4HEscLnBIHB
"""

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

air_data = pd.read_excel('air data.xlsx', parse_dates= ['DATE','TIME'])

air_data.head()

air_data[air_data.isnull().any(axis=1)].shape

air_data.shape

air_data = air_data.dropna(axis=0)

air_data.shape

features=list(air_data.columns)

features.remove('DATE')
features.remove('TIME')
features.remove('NAME')
features.remove('CATEGORY')

X = air_data[features]
y = air_data['PM2_MAX']

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.4, random_state=0)

print(X_train.shape, y_train.shape)

from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import mean_squared_error
from math import sqrt
from sklearn.metrics import r2_score
import numpy

tree = DecisionTreeRegressor(max_depth=3)
tree.fit(X_train, y_train)

y_train_pred = tree.predict(X_train)
y_test_pred = tree.predict(X_test)

print('MSE train: %.3f, test: %.3f' % (
        mean_squared_error(y_train, y_train_pred),
        mean_squared_error(y_test, y_test_pred)))
print('R^2 train: %.3f, test: %.3f' % (
        r2_score(y_train, y_train_pred),
        r2_score(y_test, y_test_pred)))

